package com.nuvio.app.features.player

import com.nuvio.app.core.storage.DesktopPrefsStorage
import kotlinx.serialization.json.JsonObject

internal actual object PlayerSettingsStorage {
    actual fun loadShowLoadingOverlay(): Boolean? = DesktopPrefsStorage.getBoolean("ps_show_loading_overlay")
    actual fun saveShowLoadingOverlay(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_show_loading_overlay", enabled)
    actual fun loadResizeMode(): String? = DesktopPrefsStorage.getString("ps_resize_mode")
    actual fun saveResizeMode(mode: String) = DesktopPrefsStorage.putString("ps_resize_mode", mode)
    actual fun loadHoldToSpeedEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_hold_speed_enabled")
    actual fun saveHoldToSpeedEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_hold_speed_enabled", enabled)
    actual fun loadHoldToSpeedValue(): Float? = DesktopPrefsStorage.getFloat("ps_hold_speed_value")
    actual fun saveHoldToSpeedValue(speed: Float) = DesktopPrefsStorage.putFloat("ps_hold_speed_value", speed)
    actual fun loadPreferredAudioLanguage(): String? = DesktopPrefsStorage.getString("ps_preferred_audio_lang")
    actual fun savePreferredAudioLanguage(language: String) = DesktopPrefsStorage.putString("ps_preferred_audio_lang", language)
    actual fun loadSecondaryPreferredAudioLanguage(): String? = DesktopPrefsStorage.getString("ps_secondary_audio_lang")
    actual fun saveSecondaryPreferredAudioLanguage(language: String?) { if (language != null) DesktopPrefsStorage.putString("ps_secondary_audio_lang", language) else DesktopPrefsStorage.remove("ps_secondary_audio_lang") }
    actual fun loadPreferredSubtitleLanguage(): String? = DesktopPrefsStorage.getString("ps_preferred_sub_lang")
    actual fun savePreferredSubtitleLanguage(language: String) = DesktopPrefsStorage.putString("ps_preferred_sub_lang", language)
    actual fun loadSecondaryPreferredSubtitleLanguage(): String? = DesktopPrefsStorage.getString("ps_secondary_sub_lang")
    actual fun saveSecondaryPreferredSubtitleLanguage(language: String?) { if (language != null) DesktopPrefsStorage.putString("ps_secondary_sub_lang", language) else DesktopPrefsStorage.remove("ps_secondary_sub_lang") }
    actual fun loadSubtitleTextColor(): String? = DesktopPrefsStorage.getString("ps_sub_text_color")
    actual fun saveSubtitleTextColor(colorHex: String) = DesktopPrefsStorage.putString("ps_sub_text_color", colorHex)
    actual fun loadSubtitleOutlineEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_sub_outline")
    actual fun saveSubtitleOutlineEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_sub_outline", enabled)
    actual fun loadSubtitleFontSizeSp(): Int? = DesktopPrefsStorage.getInt("ps_sub_font_size")
    actual fun saveSubtitleFontSizeSp(fontSizeSp: Int) = DesktopPrefsStorage.putInt("ps_sub_font_size", fontSizeSp)
    actual fun loadSubtitleBottomOffset(): Int? = DesktopPrefsStorage.getInt("ps_sub_bottom_offset")
    actual fun saveSubtitleBottomOffset(bottomOffset: Int) = DesktopPrefsStorage.putInt("ps_sub_bottom_offset", bottomOffset)
    actual fun loadStreamReuseLastLinkEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_reuse_last_link")
    actual fun saveStreamReuseLastLinkEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_reuse_last_link", enabled)
    actual fun loadStreamReuseLastLinkCacheHours(): Int? = DesktopPrefsStorage.getInt("ps_reuse_cache_hours")
    actual fun saveStreamReuseLastLinkCacheHours(hours: Int) = DesktopPrefsStorage.putInt("ps_reuse_cache_hours", hours)
    actual fun loadDecoderPriority(): Int? = DesktopPrefsStorage.getInt("ps_decoder_priority")
    actual fun saveDecoderPriority(priority: Int) = DesktopPrefsStorage.putInt("ps_decoder_priority", priority)
    actual fun loadMapDV7ToHevc(): Boolean? = DesktopPrefsStorage.getBoolean("ps_map_dv7_hevc")
    actual fun saveMapDV7ToHevc(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_map_dv7_hevc", enabled)
    actual fun loadTunnelingEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_tunneling")
    actual fun saveTunnelingEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_tunneling", enabled)
    actual fun loadStreamAutoPlayMode(): String? = DesktopPrefsStorage.getString("ps_autoplay_mode")
    actual fun saveStreamAutoPlayMode(mode: String) = DesktopPrefsStorage.putString("ps_autoplay_mode", mode)
    actual fun loadStreamAutoPlaySource(): String? = DesktopPrefsStorage.getString("ps_autoplay_source")
    actual fun saveStreamAutoPlaySource(source: String) = DesktopPrefsStorage.putString("ps_autoplay_source", source)
    actual fun loadStreamAutoPlaySelectedAddons(): Set<String>? = DesktopPrefsStorage.getStringSet("ps_autoplay_addons")
    actual fun saveStreamAutoPlaySelectedAddons(addons: Set<String>) = DesktopPrefsStorage.putStringSet("ps_autoplay_addons", addons)
    actual fun loadStreamAutoPlaySelectedPlugins(): Set<String>? = DesktopPrefsStorage.getStringSet("ps_autoplay_plugins")
    actual fun saveStreamAutoPlaySelectedPlugins(plugins: Set<String>) = DesktopPrefsStorage.putStringSet("ps_autoplay_plugins", plugins)
    actual fun loadStreamAutoPlayRegex(): String? = DesktopPrefsStorage.getString("ps_autoplay_regex")
    actual fun saveStreamAutoPlayRegex(regex: String) = DesktopPrefsStorage.putString("ps_autoplay_regex", regex)
    actual fun loadStreamAutoPlayTimeoutSeconds(): Int? = DesktopPrefsStorage.getInt("ps_autoplay_timeout")
    actual fun saveStreamAutoPlayTimeoutSeconds(seconds: Int) = DesktopPrefsStorage.putInt("ps_autoplay_timeout", seconds)
    actual fun loadSkipIntroEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_skip_intro")
    actual fun saveSkipIntroEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_skip_intro", enabled)
    actual fun loadAnimeSkipEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_anime_skip")
    actual fun saveAnimeSkipEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_anime_skip", enabled)
    actual fun loadAnimeSkipClientId(): String? = DesktopPrefsStorage.getString("ps_anime_skip_client_id")
    actual fun saveAnimeSkipClientId(clientId: String) = DesktopPrefsStorage.putString("ps_anime_skip_client_id", clientId)
    actual fun loadIntroDbApiKey(): String? = DesktopPrefsStorage.getString("ps_introdb_api_key")
    actual fun saveIntroDbApiKey(apiKey: String) = DesktopPrefsStorage.putString("ps_introdb_api_key", apiKey)
    actual fun loadIntroSubmitEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_intro_submit")
    actual fun saveIntroSubmitEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_intro_submit", enabled)
    actual fun loadStreamAutoPlayNextEpisodeEnabled(): Boolean? = DesktopPrefsStorage.getBoolean("ps_autoplay_next")
    actual fun saveStreamAutoPlayNextEpisodeEnabled(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_autoplay_next", enabled)
    actual fun loadStreamAutoPlayPreferBingeGroup(): Boolean? = DesktopPrefsStorage.getBoolean("ps_autoplay_binge")
    actual fun saveStreamAutoPlayPreferBingeGroup(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_autoplay_binge", enabled)
    actual fun loadNextEpisodeThresholdMode(): String? = DesktopPrefsStorage.getString("ps_next_ep_threshold_mode")
    actual fun saveNextEpisodeThresholdMode(mode: String) = DesktopPrefsStorage.putString("ps_next_ep_threshold_mode", mode)
    actual fun loadNextEpisodeThresholdPercent(): Float? = DesktopPrefsStorage.getFloat("ps_next_ep_threshold_pct")
    actual fun saveNextEpisodeThresholdPercent(percent: Float) = DesktopPrefsStorage.putFloat("ps_next_ep_threshold_pct", percent)
    actual fun loadNextEpisodeThresholdMinutesBeforeEnd(): Float? = DesktopPrefsStorage.getFloat("ps_next_ep_threshold_min")
    actual fun saveNextEpisodeThresholdMinutesBeforeEnd(minutes: Float) = DesktopPrefsStorage.putFloat("ps_next_ep_threshold_min", minutes)
    actual fun loadUseLibass(): Boolean? = DesktopPrefsStorage.getBoolean("ps_use_libass")
    actual fun saveUseLibass(enabled: Boolean) = DesktopPrefsStorage.putBoolean("ps_use_libass", enabled)
    actual fun loadLibassRenderType(): String? = DesktopPrefsStorage.getString("ps_libass_render")
    actual fun saveLibassRenderType(renderType: String) = DesktopPrefsStorage.putString("ps_libass_render", renderType)
    actual fun exportToSyncPayload(): JsonObject = JsonObject(emptyMap())
    actual fun replaceFromSyncPayload(payload: JsonObject) {}
}
